name: CI

on:
  push:
    branches: [main, next]
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node_modules
        run: npm ci

      - name: build
        run: npm run build

      - name: Get server folder
        id: serverDir
        run: |
          if [ $IS_MAIN ]
          then
            echo "SERVER_DIR=./public_html/lenny.fyi/" >> $GITHUB_OUTPUT
          else
            echo "SERVER_DIR=./public_html/qa.lenny.fyi/" >> $GITHUB_OUTPUT
          fi
        env:
          IS_MAIN: ${{ github.ref == 'refs/heads/main' }}

      - name: Deploy build to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./dist/
          server-dir: ${{ steps.serverDir.outputs.SERVER_DIR }}
